# curl -c cookies.txt -X POST http://localhost:3000/auth/verify-otp \
#   -H "Content-Type: application/json" \
#   -d '{"loginSessionId":"2o4b1e","otp":"866411"}'


#   curl -X POST http://localhost:3000/auth/login \
#   -H "Content-Type: application/json" \
#   -d '{"email":"<akdev@example.com","password":"12345"}'

# Uses the cookie captured in Task 2
# curl -b cookies.txt -X POST http://localhost:3000/auth/token


# Replace <jwt> with the token from Task 3
# curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ijxha2RldkBleGFtcGxlLmNvbSIsInNlc3Npb25JZCI6IjJvNGIxZSIsImlhdCI6MTc3MDk3Mzc2OSwiZXhwIjoxNzcwOTc0NjY5fQ.w1z-fu5ywYsbHRMptna0lsT47gD6wlVSfZggByiFbvw http://localhost:3000/protected